language: shell
matrix:
  include:
    - name: "Linux (Docker) Python 3.6"
      os: linux
      sudo: required
      services: docker
      env: PYTHON_VERSION=3.6
    - name: "Linux (Docker) Python 3.7"
      os: linux
      sudo: required
      services: docker
      env: PYTHON_VERSION=3.7
    - name: "Windows Python latest"
      os: windows
before_install:
  - if [[ "$TRAVIS_OS_NAME" == windows ]]; then powershell Set-ExecutionPolicy RemoteSigned; fi
  - if [[ "$TRAVIS_OS_NAME" == windows ]]; then powershell ci/nt/before_install.ps1; else ci/nix/before_install; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == windows ]]; then powershell ci/nt/install.ps1; else ci/nix/install; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == windows ]]; then powershell ci/nt/script.ps1; else ci/nix/script; fi
