version: 2

shared: &shared
  machine: true
  working_directory: ~/KVM48
  steps:
    - checkout
    - run: ci/install
    - run: ci/script

server-shared: &server-shared
  worker_directory: ~/KVM48/server
  steps:
    - run: apt update && apt install -y --no-install-recommends git
    - checkout
    - run: pip install -r server/requirements.txt pytest
    - run: cd server && python -m pytest
    - run: server/crawler.py --limit-pages 3

jobs:
  py36:
    environment:
      PYTHON_VERSION: 3.6
    <<: *shared

  py37:
    environment:
      PYTHON_VERSION: 3.7
    <<: *shared

  server-py36:
    docker:
      - image: python:3.6-slim
    <<: *server-shared

  server-py37:
    docker:
      - image: python:3.7-slim
    <<: *server-shared

workflows:
  version: 2

  build:
    jobs:
      - py36
      - py37
      - server-py36
      - server-py37

  nightly:
    triggers:
      - schedule:
          cron: "0 16 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - py36
      - py37
      - server-py36
      - server-py37
