#!/usr/bin/env bash
set -e
[[ $PYTHON_VERSION == 3.* ]] || { echo "[ERROR] Invalid PYTHON_VERSION $PYTHON_VERSION" >&2; exit 1; }
mkdir -p data
cat > data/kvm48-config.yml <<'EOF'
group_id: 10
names:
- 陈观慧
- 陈思
- 戴萌
- 孔肖吟
- 李宇琪
- 莫寒
- 钱蓓婷
- 邱欣怡
- 吴哲晗
- 徐晨辰
- 许佳琪
- 张语格
span: 3
directory: /data
named_subdirs: true
update_checks: off
EOF

sudo docker run -it --rm -v "$PWD/data:/data" "snh48live/kvm48:master-python-$PYTHON_VERSION" --debug --config data/kvm48-config.yml
sudo rm -f data/*/*.mp4

# Test a known date range with both mp4 and m3u8 URLs to download.
sudo docker run -it --rm -v "$PWD/data:/data" "snh48live/kvm48:master-python-$PYTHON_VERSION" --debug --config data/kvm48-config.yml --from 2018-10-25 --to 2018-10-27
sudo rm -f data/*/*.mp4

rm data/kvm48-config.yml
ls -lh data
